export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PROJECTS = "GET_USER_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const ADD_USER_TO_PROJECT = "ADD_USER_TO_PROJECT";
export const REMOVE_USER_FROM_PROJECT = "REMOVE_USER_FROM_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const TOGGLE_USER_PREFERENCE = "TOGGLE_USER_PREFERENCE";
export const SEND_ALERT = "SEND_ALERT";
export const SEND_PENDING_REQUEST = "SEND_PENDING_REQUEST";
export const CLOSE_PENDING_REQUEST = "CLOSE_PENDING_REQUEST";
export const SEND_PENDING_REQUEST_VALIDATE = "SEND_PENDING_REQUEST_VALIDATE";
export const CLOSE_PENDING_REQUEST_VALIDATE = "CLOSE_PENDING_REQUEST_VALIDATE";

